name: default

dependencies:
  - h5py
  - ipykernel
  - ipympl
  - ipywidgets
  - matplotlib
  - numpy
  - s3fs
  - scikit-image
  - threadpoolctl
  - tqdm
  - zarr
  - pip:
    - finufft
    - ismrmrd
    - torch>=2.0.0
