channels:
  - conda-forge
dependencies:
  - h5py
  - ipykernel
  - ipympl
  - ipywidgets
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pre-commit
  - ruff
  - s3fs
  - scipy
  - scikit-image
  - threadpoolctl
  - tqdm
  - zarr
  - pip:
    - finufft
    - ismrmrd
    - torch>=2.0.0
    - torch_geometric
