# Model parameters
num_unroll_blocks: 10
num_res_blocks: 15
CG_Iter: 10
activation: "ReLU"
features: 512

# Loss function parameters
weight_kspace_loss: [0.5, 0.5]
weight_ispace_loss: [0.1, 0.1]
weight_hankel_loss: [0.0, 0.01]
weight_casorati_loss: [0.0, 0.0]
normalized_loss: true

# Training parameters
epochs: 25
model_training: true
model_validation: false
ema_decay: 0.9
fractions: [0.0, 0.5, 0.5]

save_checkpoint: true
checkpoint_frequency: 10

load_model_state: true
load_averaged_model_state: true
load_optim_state: true
load_metrics: true

disable_progress_bar: true
timing_level: 0
validation_level: 0

num_threads: 24
num_cpu_per_worker: 24
num_gpu_per_worker: 0
num_workers: 1
group_size: 1
use_gpu: false
device: "cpu"

data_dir: ""
data_backend: "local"
model_dir: ""
model_backend: "local"
image_dir: ""
image_backend: "local"
endpoint_url: "https://s3.fz-juelich.de"

datasets: []
slices:
  start:
  stop:
  step:
shape: []
num_spokes: 8
